name: codex
base: core24
summary: Codex - One agent for everywhere you code
adopt-info: codex
description: |
  Codex is OpenAI’s coding agent for software development. ChatGPT Plus,
  Pro, Business, Edu, and Enterprise plans include Codex.
grade: stable
confinement: strict
platforms:
  amd64:
  arm64:
source-code: https://github.com/nysasounds/codex
issues: https://github.com/nysasounds/codex/issues
license: Apache-2.0

parts:
  codex:
    plugin: rust
    source: https://github.com/openai/codex.git
    source-tag: rust-v0.104.0
    source-depth: 1
    source-subdir: codex-rs
    override-pull: |
      craftctl default
      tag="$(git -C "${CRAFT_PART_SRC}" describe --tags --exact-match 2>/dev/null || git -C "${CRAFT_PART_SRC}" describe --tags --abbrev=0)"
      craftctl set version="${tag#rust-v}"

    rust-channel: stable
    rust-use-global-lto: false
    rust-cargo-parameters:
      - "--bin codex"
    build-packages:
      - lld
      - pkg-config
      - libssl-dev
      - libclang-dev
      - libcap-dev
    stage-packages:
      - xdg-utils
    build-environment:
      - RUSTFLAGS: "-C link-arg=-fuse-ld=lld"
      - CARGO_PROFILE_RELEASE_CODEGEN_UNITS: "1"
      - CARGO_PROFILE_RELEASE_DEBUG: "0"
    override-build: |
      craftctl default
      # Include the current license info #
      install -d "${CRAFT_PART_INSTALL}/usr/share/doc/${CRAFT_PROJECT_NAME}"
      install "${CRAFT_PART_SRC}/LICENSE" "${CRAFT_PART_INSTALL}/usr/share/doc/${CRAFT_PROJECT_NAME}/"
      install "${CRAFT_PART_SRC}/NOTICE" "${CRAFT_PART_INSTALL}/usr/share/doc/${CRAFT_PROJECT_NAME}/"
    organize:
      codex: bin/codex
  # As this is a sctricly confined snap - include some commonly used utils #
  utils:
    plugin: nil
    stage-packages:
      - fd-find
      - git
      - gnupg
      - jq
      - less
      - ripgrep
      - unzip
      - zip
  completer:
    plugin: nil
    override-build: |
      install -d "${CRAFT_PART_INSTALL}/usr/share/bash-completion"
      ${CRAFT_STAGE}/bin/codex completion bash > "${CRAFT_PART_INSTALL}/usr/share/bash-completion/codex"
    after:
      - codex

apps:
  codex:
    command: bin/codex
    completer: usr/share/bash-completion/codex
    environment:
      CODEX_HOME: $SNAP_USER_DATA/.codex
    plugs:
      - network
      - network-bind
      - desktop
      - home
